### ISSUE TITLE
Skip displaying not currently in service routes in Dashboard provided in Home.js

### ISSUE THREAD

**Issue by chunlaw** [hkbus/hk-independent-bus-eta#10]
![image](https://user-images.githubusercontent.com/4438690/125171212-7e709580-e1e5-11eb-9545-2a1b8d51e989.png)
For example, the clock time is 01:16am, prefer to show over-night routes instead of day-service routes.

**Comment by skpracta** [comment]
They have added "show ONLY operating routes" in "Personalised settings", the issue can be closed then.
