### ISSUE TITLE
Bug: Android返回制退出唔到應用程式

### ISSUE THREAD

**Issue by pantinker** [hkbus/hk-independent-bus-eta#109]
新手用戶第一次用
想請問Android返回制退出唔到應用程式？🙏

Chun: 有待 fix

https://github.com/hkbus/hk-independent-bus-eta/assets/152949070/2d50fdf4-8393-45c2-a6bd-8675b253f201

**Comment by chakflying** [comment]
PR open in hkbus/mobile-bus-app#9

Pinging @chunlaw in case this got lost in the wind 🙇🏻‍♂️

**Comment by chakflying** [comment]
Issue can be closed as PR has been merged.
