### ISSUE TITLE
Bug: Overflow issue of long continuous text in Notification page

### ISSUE THREAD

**Issue by kosswong** [hkbus/hk-independent-bus-eta#121]
![FireShot Capture 010 - 儀表板 - 巴士到站預報 App （免費無廣告） - hkbus app](https://github.com/hkbus/hk-independent-bus-eta/assets/33596596/df554775-9948-4ea2-a838-1798f718444a)

**Suggest solution:**
Add following in line 69 of \pages\Notice.tsx
```
wordWrap: "break-word",
```

So it would be:
```
const paperSx: SxProps<Theme> = {
  display: "flex",
  flexDirection: "column",
  overflow: "auto",
  width: "100%",
  flex: 1,
  textAlign: "left",
  p: 1,
  gap: 2,
  bgcolor: "unset",
  wordWrap: "break-word",
};
```

And the page will be fixed as:
![FireShot Capture 012 - 儀表板 - 巴士到站預報 App （免費無廣告） - hkbus app](https://github.com/hkbus/hk-independent-bus-eta/assets/33596596/9f48941a-26d2-4aef-b528-03d7da5511f7)

**Comment by pantinker** [comment]
It is also a related closed issue https://github.com/hkbus/hk-independent-bus-eta/issues/131
