### ISSUE TITLE
Bug: [Mobile] Back button cannot close Modals

### ISSUE THREAD

**Issue by chakflying** [hkbus/hk-independent-bus-eta#122]
## Description

Back button on mobile cannot close Modals, and instead change the location of the page in background. This leads to very strange behaviour in Settings -> "管理收藏" -> "顯示時間". This is because opening Modals only update the DOM, but the back button relies on navigation through the browser history stack.

## Possible Solution

Maybe we can wrap the Modal component to modify the history stack on open/close, as suggested in [mui/material-ui#12759](https://github.com/mui/material-ui/issues/12759). But it seems quite complicated as we would need to prevent duplicate entries from polluting the history.

**Comment by pantinker** [comment]
It is also related to closed issue #109
https://github.com/hkbus/hk-independent-bus-eta/issues/109
