### ISSUE TITLE
Issue: 對頭線功能

### ISSUE THREAD

**Issue by ArHei** [hkbus/hk-independent-bus-eta#126]
Issue: 對頭線功能

Route: 17M van

Search 17M, will return
*1 17M 往 寶琳站
*2 17M 往 九龍醫院
*3 17M 往 翠林
*4 17M(特別班) 往 寶琳站(經康寶路)
*5 17M(特別班) 往 通菜街

if click on *2 "往 九龍醫院", then click on 對頭線, will continue between *1 "往 翠林" and *3 "往 寶琳站", cannot get back to *2 "往 九龍醫院".
actually "往 九龍醫院" is 循環線, no 對頭線.

Maybe caused by data issue.

**Comment by chunlaw** [comment]
Fixed in latest commit
