### ISSUE TITLE
Feature request: 美化 "通告” 的 url 顯示方式

### ISSUE THREAD

**Issue by pantinker** [hkbus/hk-independent-bus-eta#131]
Ethan Lam:
Date: 2024-01-07

![IMG_20240107_120220_298.jpg](https://github.com/hkbus/hk-independent-bus-eta/assets/152949070/5eb0d5e4-7155-4905-b53c-88017963930b)

雖然似乎是一線通的來源資料問題，但可以考慮用 parser 簡單整理一下 html 才放上 hkbus 的版面

Possible solution:

JavaScript parsing libraries:
https://scrapeops.io/nodejs-web-scraping-playbook/best-nodejs-html-parsing-libraries/

**Comment by chunlaw** [comment]
This is a bug from data source, there is no issue when you change to ENG

**Comment by pantinker** [comment]
但係中文版本應該較多人用吧？

明白這是 data source 的問題，但要解決不是太難吧？
