### ISSUE TITLE
problem: 巴士站搬了新位置，但路線圖的紅線仍是舊的走線

### ISSUE THREAD

**Issue by chokhocheung** [hkbus/hk-independent-bus-eta#132]
以九巴74X往大埔為例，新蒲崗四美街的車站已搬往啟翔苑，車站列表是正確的，但路線圖的紅線仍顯示巴士兜入四美街而不是啟翔苑。

![IMG_20240107_195318](https://github.com/hkbus/hk-independent-bus-eta/assets/101919798/e3165877-7c6d-407c-a28e-9afd087c33c7)

**Comment by kaon** [comment]
probably CSDI data source issue.
