### ISSUE TITLE
Custom range slider cannot set new value

### ISSUE THREAD

**Issue by maruk0chan** [hkbus/hk-independent-bus-eta#133]
Found that if the range is some numbers other than 0, it needs to be changed to new number which is much greater (like a few steps but still not sure) than the old one to be effective.

For example, it doesn't work changing it from 2km to 1.25km but 1km.

It seems that the new value is being forced to change to a new value that needs to be a few steps away the old one.

**Comment by kaon** [comment]
Two more issues:
1. Range should not starts with 0.
2. Graphical representation is meaningless when range exceeds 4km.
