### ISSUE TITLE
Feature Request: add a link to the route agency website

### ISSUE THREAD

**Issue by DeepAQ** [hkbus/hk-independent-bus-eta#150]
Some bus routes like R33 do not have a fixed schedule, and passengers need to read the latest announcements on the agency website. The agency website URL for each route is already included in [the Transport Department dataset](https://data.gov.hk/tc-data/dataset/hk-td-tis_11-pt-headway-en), it would be better if a link can be added to this app. I would love to contribute to the code if we agree on this.

**Comment by chunlaw** [comment]
You may commit your code, I will revise it. Thank you.

**Comment by DeepAQ** [comment]
3 pull requests have been created for this feature.

**Comment by chunlaw** [comment]
Resolved
