### ISSUE TITLE
Ask for opinion / discussion: UK London version

### ISSUE THREAD

**Issue by hermanho** [hkbus/hk-independent-bus-eta#156]
Thank you very much to @chunlaw for founding the project and the contributions from all contributors. It is a great eta app.

I would like to folk it and make a UK London version. I would like you and other contributors advise.

**Comment by chunlaw** [comment]
I have no idea about the data sources of ETA data in London. Anyway, this project is under GPL-3, feel free to folk it and modify for your own project.

**Comment by xavier114fch** [comment]
You should know how to get the necessary data and transform them to power the frontend in this repo. You may take a look at the data crawling repo.
[https://github.com/hkbus/hk-bus-crawling](https://github.com/hkbus/hk-bus-crawling)

TfL has their unified APIs that allows you to get all the route and ETA details for nearly all services under TfL. They have provided a Postmen collection and SwaggerHub documentation for easy reference. 
[https://tfl.gov.uk/info-for/open-data-users/unified-api](https://tfl.gov.uk/info-for/open-data-users/unified-api)

Non-TfL bus services also exist in London, especially for the outer London boroughs. You may consider using national data for these services.

There are plenty of ETA service and websites in the UK using open data. **Bustimes** is one of them and it is by far a very comprehensive and well-transformed data source. If you want to know the open data sources, the links on this page can help.
[https://bustimes.org/data](https://bustimes.org/data)
