### ISSUE TITLE
[Stops] Display tab in reverse order

### ISSUE THREAD

**Issue by tommykamkcm** [hkbus/hk-independent-bus-eta#157]
Steps to reproduce:
1. Go to "Manage Collections > Stops"
2. Update the order, say A1 on top, then A2, A3
3. Go back to the home page's "Stops" tab

Observation:
- Stops are displayed as A3, A2, A1

Expected Results:
- The ordering should match with the DnD list in the setting screen

**Comment by thomas930** [comment]
Any screenshots can be uploaded and shown here?

**Comment by tommykamkcm** [comment]
1. Manage Collections > Stops
<img width="444" alt="image" src="https://github.com/hkbus/hk-independent-bus-eta/assets/1722447/b354ad83-6747-4350-90cf-608f63c50b5e">

2. Home > Stops
<img width="444" alt="image" src="https://github.com/hkbus/hk-independent-bus-eta/assets/1722447/67e224f6-4f8a-460a-b58f-81d20e342842">

**Comment by tommykamkcm** [comment]
Thanks guys! Closing this issue.
