### ISSUE TITLE
城巴 黃線畫黃路，其實近乎睇唔到條線🙈🙏

### ISSUE THREAD

**Issue by chengkeith** [hkbus/hk-independent-bus-eta#158]
Original report at https://t.me/hkbusapp/12438

城巴 黃線畫黃路，其實近乎睇唔到條線🙈🙏

![image](https://github.com/hkbus/hk-independent-bus-eta/assets/15365495/d403b8c6-aa4f-4ca7-a9b3-9f0b28779114)

**Comment by pantinker** [comment]
謝謝記下 issue。麻煩下次不要指回 TG msg, 尤其不要指向 TG account. TG 留言的朋友未必想公開佢的聯絡方法

**Comment by chengkeith** [comment]
多謝你嘅意見，如果淨係指向對話，而唔指向網友的 account ，是否 ok？

我見你之前幫手 log case 都有 quote 到係邊位網友匯報問題，我都係跟返你個 format。而因為我用手機 copy，係唔容易 copy 佢網名(display name)，反而佢 tg @username 就好易 copy 到，而且呢位網友佢個網名仲要係奇怪字體嘅字

經過尋晚 tg 嘅討論，我諗啲人揀去 tg 匯報問題純粹係因為冇 GitHub account，而個 app 本身都係提供 tg 連結叫人入去報錯 ，相關網友未必係因為想隱藏佢嘅聯絡方式而唔喺 GitHub 度落 case (講真你去得 tg 講，人地都搵到你啦)，但如果你好唔想我咁做，我可以淨係指返去 tg 對話嘅 link，都係方便追尋返當時個討論同相關問題嘅 description

**Comment by pantinker** [comment]
Mmm.... 明白你的用心，想要連結回到 TG  討論上面，方便日後追查。

TG group上的討論和 github issue 最大的分別，在於 GitHub issue 是公開給全世界，搜尋器會找得到，任何人都可以見到。

TG group 上的討論，則只有 group友見得到，不入 group 就不能看見。而且 TG 留言，作者可以隨時刪除。

因為有這個分別，這即是說，把 TG group 的留言抄到這裡，這個留言就會透露給全世界，而且可能永遠不會在網絡上消失。（例如被 google、Microsoft、GitHub backup)

起碼我自己就覺得，TG group 上留言的朋友，心裡面是沒有預計有這個後果。假如放TG留言連結在這裡，很容易就會找到留言作者，即使留言作者改了TG名，就算改了 username 也會找得到。這不會是留言者的期望吧？

舉個不完全恰當的比喻：公司同事群組的Whatsapp 討論，參與者不會預期會透露給第三者吧？如果要透露給第三者甚或傳媒，最好要徵得作者同意吧？

先此聲明：小弟只是這個project 其中一位參與者，各人也可以用自己方式提交 issue。TG 設計是匿名留言，留言很快就湮沒。將留言內容放這裡是一個折衷辦法，方便 developer 跟進。但如果因此會透露 TG 用家的聯絡方法，我想這不是留言者預期的事。

**Comment by chengkeith** [comment]
明白的，我都同意你嘅觀點，我其實完全唔介意只係複製有關問題的文字內容(同截圖)，但我唔想搶咗人地 credit 好似個 suggestion 係由我提出咁

我見你之前幫手起 issue 都會 quote 返網友的TG名稱，我見你咁做覺得幾好先至跟返咁做。我原意都係想盡跟你嘅做法，不過我用手機 tg app 就唔係咁容易可以 highlight 網友個網名去 copy，你有冇咩好提議？

我第一次幫手起 issue，都係諗住個 project 大家有份就互相幫輕吓，個格式可能大家未有共識，feel free to disucss  :)

**Comment by thomas930** [comment]
直接動起來入Pull Request 啦~
改色應該比較簡單~

**Comment by thomas930** [comment]
己入PR #162 ，歡迎比意見。^^

**Comment by pantinker** [comment]
> 我見你之前幫手起 issue 都會 quote 返網友的TG名稱，我見你咁做覺得幾好先至跟返咁做。我原意都係想盡跟你嘅做法，不過我用手機 tg app 就唔係咁容易可以 highlight 網友個網名去 copy，你有冇咩好提議？

其實我並沒有好方法，做法好原始。同你的做法差唔多，只係在 TG 按多幾下咁 copy。android 上的 google keyboard, clipboard 可以有 history. 咁我就一次過放晒入clipboard, 然後在 GitHub app 慢慢排返好佢。

> 我第一次幫手起 issue，都係諗住個 project 大家有份就互相幫輕吓，個格式可能大家未有共識，feel free to disucss  :)

有諗過好唔好整張固定格式的問題 msg, 即係好似算命 TG group 咁：

歡迎對命理有興趣嘅您，一齊論命交流心得；歡迎問命者留低出生年月日時、出生地、性別及所問事情，然後耐心等待有緣嘅朋友回覆問命。
請注意，論命者提供的資訊只供參考，問命者須詳閱本谷之 Group Info。

為方便各位師兄師姐, 唔駛逐位逐項追問，請問命者填好以下 #表格 各項︰
出生年月日︰         (若是農曆請註明) 
出生時︰       (幾點幾分 am / pm)
出生地：hk      (城市)
性別︰
是否命主本人︰  
如非命主本人，請簡介其人資料及與命主的關係：
所問事情︰


不過 bug 同 feature request 好多時溝埋一齊，叫人填表會有點煩厭

**Comment by pantinker** [comment]
> 我見你之前幫手起 issue 都會 quote 返網友的TG名稱，我見你咁做覺得幾好先至跟返咁做。我原意都係想盡跟你嘅做法，不過我用手機 tg app 就唔係咁容易可以 highlight 網友個網名去 copy，你有冇咩好提議？

其實我並沒有好方法，做法好原始。同你的做法差唔多，只係在 TG 按多幾下咁 copy。android 上的 google keyboard, clipboard 可以有 history. 咁我就一次過放晒入clipboard, 然後在 GitHub app 慢慢排返好佢。

> 我第一次幫手起 issue，都係諗住個 project 大家有份就互相幫輕吓，個格式可能大家未有共識，feel free to disucss  :)

有諗過好唔好整張固定格式的問題 msg, 即係好似算命 TG group 咁：

> 歡迎對命理有興趣嘅您，一齊論命交流心得；歡迎問命者留低出生年月日時、出生地、性別及所問事情，然後耐心等待有緣嘅朋友回覆問命。
請注意，論命者提供的資訊只供參考，問命者須詳閱本谷之 Group Info。

> 為方便各位師兄師姐, 唔駛逐位逐項追問，請問命者填好以下 #表格 各項︰
> 出生年月日︰         (若是農曆請註明) 
> 出生時︰       (幾點幾分 am / pm)
> 出生地：hk      (城市)
> 性別︰
> 是否命主本人︰  
> 如非命主本人，請簡介其人資料及與命主的關係：
> 所問事情︰


不過 bug 同 feature request 好多時溝埋一齊，叫人填表會有點煩厭
