### ISSUE TITLE
No arrival times (2024-08-15)

### ISSUE THREAD

**Issue by git-tiger** [hkbus/hk-independent-bus-eta#197]
The app has stopped showing times. I still have my list of bus stops, but no update on arrival times.

**Comment by chunlaw** [comment]
data.gov.hk is now blocking the access to KMB ETA from web applications in other domains.

The official hkbus.app is now temporarily using Clodflare worker to handle it. You may update the app by going to Settings and click Version.

**Comment by loleungweb** [comment]
> data.gov.hk is now blocking the access to KMB ETA from web applications in other domains.
> 
> The official hkbus.app is now temporarily using Clodflare worker to handle it. You may update the app by going to Settings and click Version.

唔可以由其他DOMAIN 攞data,咁就唔係api啦,係api有問題?佢地維修緊?
