### ISSUE TITLE
Bus predicted arrival time can not load

### ISSUE THREAD

**Issue by maxso-216** [hkbus/hk-independent-bus-eta#62]
Starting from recent, I have found out the arrival data can not be loaded. Here is the screenshot.
![_20220704_064357](https://user-images.githubusercontent.com/107261566/177059801-00be475c-3f62-4a25-8da6-fa50063bc548.JPG)

However, data on home can be loaded.
![_20220704_064518](https://user-images.githubusercontent.com/107261566/177059817-a392d359-df93-4ae7-be53-06b93efb7ddb.JPG)

I am using Firefox Nightly 102.0a1, on Android 9, with UBlock Origin addson.

**Comment by maxso-216** [comment]
Seem solved. Close issue

**Comment by hk-ng** [comment]
I think is due to unexpected data from government from 02:00 to 06:00.
Please make sure the issue is solved before closing issue.

**Comment by maxso-216** [comment]
Recheck, Solved. But will it be better there's a fallback backed, when gov server is not available, directly fetch data from bus companies website?
