### ISSUE TITLE
Migrating to Vite

### ISSUE THREAD

**Issue by chunlaw** [hkbus/hk-independent-bus-eta#73]
Try a bit, but failed to migrate the `service-worker.js`, no time to drag on :'(

**Comment by thomassth** [comment]
actually I found it easier in vite

Try this vite plugin https://vite-pwa-org.netlify.app/

**Comment by chunlaw** [comment]
@thomassth Yes, I have tried it. It is indeed much easier to set up in fresh. 

However, current user (react-scripts) will experience app crash after the host changed to Vite.

**Comment by chunlaw** [comment]
Done in commit [a963d2](https://github.com/hkbus/hk-independent-bus-eta/commit/a963d224b40bb8edbcd14ce07b9cd032836dfd00)
