### ISSUE TITLE
UI: iPhone PWA 整頁拖動

### ISSUE THREAD

**Issue by ApophisLee** [hkbus/hk-independent-bus-eta#81]
https://github.com/hkbus/hk-independent-bus-eta/assets/2356831/e9ef826f-7f74-495b-bb25-0c2d86aa54ef

**Comment by chunlaw** [comment]
Thank you for reporting it, I will review this issue

**Comment by chunlaw** [comment]
Fixed in latest commit. 

You may try it in https://alpha.hkbus.app first
