### ISSUE TITLE
Home Screen icon on iOS has black background

### ISSUE THREAD

**Issue by kkoyung** [hkbus/hk-independent-bus-eta#82]
### Issue
After installing PWA on iOS, the home screen icon of hkbus.app has a black square background with rounded corners, behind the circular yellow icon. The yellow background of the icon is expected to extend to the rounded corners.

### Screenshots

![Screenshot 2023-12-02 at 16 35 00](https://github.com/hkbus/hk-independent-bus-eta/assets/11942650/8df525a1-f972-42a0-9e5a-77a5b83b0a74)

### Steps to Reproduce
1. Enter https://hkbus.app on iOS Safari.
2. Click the share button, and click "Add to Home Screen".

### Versions

hkbus.app 11.1.0-0d281ab
iOS 17.1.2

**Comment by chunlaw** [comment]
The [latest commit](https://github.com/hkbus/hk-independent-bus-eta/commit/4e5e726064ae39efa094280d971027b77dcc9fab) has updated the PWA icons.

Fyi, the website will be updated tomorrow automatically, you may need to redo the "Add to Home Screen" process tomorrow.

**Comment by kkoyung** [comment]
@chunlaw The issue still exists on the latest commit 11.1.0-a2d6588, even after redo the "Add to Home Screen" process.

Maybe we also need to change the `<link rel="apple-touch-icon" ...>` tag, which still points to the circular icon.
https://github.com/hkbus/hk-independent-bus-eta/blob/a2d6588166ac49ccae6aec0ed4089d6f9c5b81cf/public/index.html#L57C68-L57C68

**Comment by kkoyung** [comment]
The latest commit fixed the issue. The app logo now looks good in alpha version.

Thanks for adding me to the contributor list.
