### ISSUE TITLE
How to add a widget to home screen?

### ISSUE THREAD

**Issue by Ember438** [hkbus/hk-independent-bus-eta#83]
Can this app support widget? That will be super helpful, thanks

**Comment by chunlaw** [comment]
I am sorry to tell you no. The current architecture cannot support widget.

I have reviewed the approach of developing widget at the very beginning, however, iOS 15 refreshes the widget every 15 minutes, and, even worse, iOS 14 refreshes with its own intelligence. There is large gap to give an up-to-date ETA for user. 

Therefore, I omit that approach, and taking a web app apporach with optimization for onloading speed. Hope it helps 🙏
