### ISSUE TITLE
feature request: 用戶自行指定「附近」距離 上限

### ISSUE THREAD

**Issue by pantinker** [hkbus/hk-independent-bus-eta#89]
粒子風暴：
建議 增加 指定「附近」距離 上限 選項
（例如 100 米、200 米、500 米）

建議enhance個人化
可Default「附近」做 200m，但可以選1km甚至2km(例如西貢區用户有可能)

Date: 2023-12-05

**Comment by maruk0chan** [comment]
attempt to solve this with [this PR](https://github.com/hkbus/hk-independent-bus-eta/pull/103)

**Comment by maruk0chan** [comment]
Implement with [this PR](https://github.com/hkbus/hk-independent-bus-eta/pull/117)
