### ISSUE TITLE
Problem: 城巴 702 循環線

### ISSUE THREAD

**Issue by pantinker** [hkbus/hk-independent-bus-eta#92]
Date: 2023-12-06

曦齊:
702又一城至海麗邨，唔見咗又一城至北河街的七個站😂

Chun:
https://hkbus.app/zh/route/702-1-fuk-wing-street,-yen-chow-street-hoi-lai-estate

運輸署定義為來回綫，城巴就當循環綫

所以分開咗

D Wong:
應該係將特別班次撈亂咗，因為對面方向都係變咗短途車，㩒時間表就睇到

城巴 official: 星期一至五的上課日 (公眾假期及學校假期除外) 增設 07:14 特別班次由泓景臺, 深盛路開往大坑西新邨民樂樓, 窩仔街，以及增設 07:25 特別班次由福榮街, 欽州街開往海麗邨

Chun:
先多謝支持
呢條路綫真係要個別研究😭

**Comment by kaon** [comment]
Fixed on 25 Mar 2024
