### ISSUE TITLE
Feature request: 精簡港鐵ETA顯示

### ISSUE THREAD

**Issue by pantinker** [hkbus/hk-independent-bus-eta#94]
Date: 2023-12-07

![IMG_20231207_113849_014.jpg](https://github.com/hkbus/hk-independent-bus-eta/assets/152949070/3393c385-8ef0-48ae-b4d9-7f67c97d606c)
有冇可能顯示返目的地🙏例如「落馬洲」

Loophp James 建議：
07:52 3分鐘 - ❶ 落馬洲
（或者不要hyphen)

參考
![IMG_20231207_113855_628.jpg](https://github.com/hkbus/hk-independent-bus-eta/assets/152949070/d42ea4ec-b883-49e3-8642-b0faa708c3d1)

**Comment by maruk0chan** [comment]
Changed in [PR#96](https://github.com/hkbus/hk-independent-bus-eta/pull/96).
